//--------AUTH--------
export const AUTHENTICATE = 'AUTHENTICATE';
export const SUBSCRIPTION = 'SUBSCRIPTION';

// resend_reports
export const SEARCH_GET_NA_FILE_REPORTS = 'SEARCH_GET_NA_FILE_REPORTS';
export const SEARCH_GET_NA_PROPRIETOR_REPORTS = 'SEARCH_GET_NA_PROPRIETOR_REPORTS';
export const SEARCH_GET_NA_SEARCH_REPORTS = 'SEARCH_GET_NA_SEARCH_REPORTS';
export const WATCH_GET_NA_REPORTS = 'WATCH_GET_NA_REPORTS';
export const MANAGER_GET_NA_REPORTS = 'MANAGER_GET_NA_REPORTS';

// requeue_reports
export const SEARCH_FILE_REPORTS_QUEUE = 'SEARCH_FILE_REPORTS_QUEUE';
export const SEARCH_PROPRIETOR_REPORTS_QUEUE = 'SEARCH_PROPRIETOR_REPORTS_QUEUE';
export const SEARCH_SEARCH_REPORTS_QUEUE = 'SEARCH_SEARCH_REPORTS_QUEUE';
export const WATCH_REPORTS_QUEUE = 'WATCH_REPORTS_QUEUE';
export const MANAGER_REPORTS_QUEUE = 'MANAGER_REPORTS_QUEUE';
